// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyAirport.EF;

namespace MyAirport.EF.Migrations
{
    [DbContext(typeof(MyAirportDB))]
    partial class MyAirportDBModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("LO.MyAirport.EF.Bagage", b =>
                {
                    b.Property<int>("BagageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CLASSE")
                        .IsRequired()
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("CODEIATA")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DATECREATION")
                        .HasColumnType("datetime2");

                    b.Property<string>("Destination")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Escale")
                        .HasColumnType("int");

                    b.Property<string>("SSUR")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VolId")
                        .HasColumnType("int");

                    b.HasKey("BagageId");

                    b.HasIndex("VolId");

                    b.ToTable("Bagages");
                });

            modelBuilder.Entity("LO.MyAirport.EF.Vol", b =>
                {
                    b.Property<int>("VolId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("CIE")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DES")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DHC")
                        .HasColumnType("datetime2");

                    b.Property<string>("IMM")
                        .HasColumnType("nvarchar(max)");

                    b.Property<short>("JEX")
                        .HasColumnType("smallint");

                    b.Property<string>("LIG")
                        .HasColumnType("nvarchar(max)");

                    b.Property<short>("PAX")
                        .HasColumnType("smallint");

                    b.Property<string>("PKG")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("VolId");

                    b.ToTable("Vols");
                });

            modelBuilder.Entity("LO.MyAirport.EF.Bagage", b =>
                {
                    b.HasOne("LO.MyAirport.EF.Vol", "Vol")
                        .WithMany()
                        .HasForeignKey("VolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
